services:
  nginx:
    image: nginx:alpine
    container_name: durak_na_grani
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ca.crt:/etc/ssl/ca.crt
      - ./nginx/durak-na-grani.crt:/etc/ssl/durak-na-grani.crt
      - ./nginx/durak-na-grani.key:/etc/ssl/durak-na-grani.key
