worker_processes auto;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip on;
    gzip_comp_level 6;

    server {
        listen 80;
        listen [::]:80;
        server_name _;
        server_tokens off;

        root /var/www;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
            #expires: off;
        }

        location ~ /\. {
            deny all;
        }
    }
}
